import { createContext, useContext, useState } from "react";
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  getDocs,
  collection,
  addDoc,
  getDoc,
  doc,
  collectionGroup,
  query,
  where,
  updateDoc,
  arrayUnion,
  arrayRemove,
  setDoc,
} from "firebase/firestore";
import { getAuth, onAuthStateChanged } from "firebase/auth";

// Import Required Firebase Utility

const firebaseConfig = {
  apiKey: import.meta.env.VITE_APP_API_KEY,
  authDomain: import.meta.env.VITE_APP_AUTH,
  projectId: import.meta.env.VITE_APP_PROJECT_ID,
  storageBucket: import.meta.env.VITE_APP_BUCKET,
  messagingSenderId: import.meta.env.VITE_APP_SENDER_ID,
  appId: import.meta.env.VITE_APP_APP_ID,
  measurementId: import.meta.env.VITE_APP_MEASUREMENT_ID,
};

const FirebaseContext = createContext(null);
const firebaseApp = initializeApp(firebaseConfig);
const auth = getAuth();

// Create an instance of the imported firebase utility

const db = getFirestore(firebaseApp);
let fs = getFirestore();
export const useFirebase = () => {
  return useContext(FirebaseContext);
};

export const FirebaseProvider = (props) => {
  // to store all the patients in the database
  const [allPatientData, setAllPatientData] = useState([]);

  const [patientDetail, setPatientDetail] = useState({});

  const [checkups, setCheckups] = useState([]);

  const [doctorData, setDoctorData] = useState([]);

  const [isLoggedIn, setIsLoggedIn] = useState();

  const [checkupId, setCheckupId] = useState([]);

  onAuthStateChanged(auth, (user) => {
    if (user) {
      setIsLoggedIn(true);
    } else {
      setIsLoggedIn(false);
    }
  });

  // to store the patients of one doc
  const [patientData, setPatientData] = useState([]);

  async function getDocument(collectionName, docId) {
    const snap = await getDoc(doc(db, collectionName, docId));

    if (collectionName === "patients") {
      setPatientDetail(snap.data());
    }
  }

  // get all the patients in the database
  async function getAllDocuments(collectionName) {
    try {
      // get all the documents in given collection
      const collectionData = await getDocs(collection(db, collectionName));

      // iterate through each of the document and add them to the allPatientData state
      if (collectionName === "patients") {
        // reset the allPatientData state
        setAllPatientData([]);
        collectionData.forEach((doc) => {
          setAllPatientData((prev) => {
            return [...prev, doc.data()];
          });
          console.log(doc.data());
        });
      }
    } catch (error) {
      console.log(error);
    }
  }

  // get all the patients of the given doctor
  async function getAllPatientsOf(docId) {
    try {
      // query all the patients whose doctors array contains the given docId
      const q = query(
        collection(db, "patients"),
        where("doctors", "array-contains", docId)
      );

      // store the result in a const
      const querySnapshot = await getDocs(q);

      // reset patient data state
      setPatientData([]);

      // iterate through each of the array elements and add them to the patientData state
      querySnapshot.forEach((doc) => {
        setPatientData((prev) => {
          return [...prev, doc.data()];
        });

        console.log(doc.data());
      });
    } catch (error) {
      console.log(error);
    }
  }

  async function getSubCollections(collectionName, docId, subCollectionName) {
    const itemRef = doc(db, collectionName, docId);
    const collectionRef = collection(itemRef, subCollectionName);
    const subCollectionData = await getDocs(collectionRef);

    if (collectionName === "patients" && subCollectionName == "checkups") {
      setCheckups([]);
      subCollectionData.forEach((docu) => {
        setCheckups((prev) => [...prev, docu.data()]);
        console.log(docu.data());
      });
    }
  }

  // to add doctorId reference to the patient
  async function addPatientTo(doctorId, patientId) {
    try {
      // get the document reference using the collection name and doc id
      const patientRef = doc(db, "patients", patientId);

      // update document by adding the new doctorId in the doctors array
      await updateDoc(docRef, {
        doctors: arrayUnion(doctorId),
      });
    } catch (e) {
      console.log(e);
    }
  }

  // to delete doctorId reference to the patient
  async function deletePatientfrom(doctorId, patientId) {
    try {
      // get the document reference using the collection name and doc id
      const docRef = doc(db, "patients", patientId);

      // update document by deleting the doctorId from the doctors array
      await updateDoc(docRef, {
        doctors: arrayRemove(doctorId),
      });
    } catch (e) {
      console.log(e);
    }
  }

  // to add/ update a doctor's details to the doctors collection
  async function setDoctor(data, docId) {
    try {
      // get document with a uuid generated by client
      const newUserRef = doc(db, "doctors", docId);

      // if document exists, update it, if not, add it
      await setDoc(newUserRef, data);
    } catch (e) {
      console.log(e);
    }
  }

  // to getDoctor details anywhere once the user has logged in
  async function getDoctor(doctorEmail) {
    try {
      //query for the doctor with particular email id
      const q = query(
        collection(db, "doctors"),
        where("doctorEmail", "==", doctorEmail)
      );

      // get the list of docs (there is only one, im getting error if i use getDoc() if you can solve it pls do)
      const data = await getDocs(q);

      // set the doctor data so that you can access it anywhere once the user has logged in
      data.forEach((doc) => {
        setDoctorData(doc.data());
        console.log(doc.data());
      });
    } catch (e) {
      console.log(e);
    }
  }

  //To update a document with data provided in params
  async function updateDocument(collectionName, docId, data) {
    try {
      const docRef = doc(db, collectionName, docId);
      await updateDoc(docRef, data);
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <FirebaseContext.Provider
      value={{
        // Pass the functions created to be used globally

        getAllDocuments,
        getAllPatientsOf,
        addPatientTo,
        deletePatientfrom,
        setDoctor,
        getDoctor,
        checkupId,
        isLoggedIn,
        setIsLoggedIn,
        patientData,
        patientDetail,
        doctorData,
        getSubCollections,
        checkups,
        getDocument,
        updateDocument,
        allPatientData
      }}
    >
      {props.children}
    </FirebaseContext.Provider>
  );
};
